services:
  phpdoc:
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    volumes:
      - ./:/opt/phpdoc
      # Use the container vendor folder not the one from ./
      - /opt/phpdoc/vendor
    working_dir: "/opt/phpdoc"
  phpdoc-pcov:
    build:
      context: .
      target: dev-pcov
      dockerfile: Dockerfile
    volumes:
      - ./:/opt/phpdoc
      # Use the container vendor folder not the one from ./
      - /opt/phpdoc/vendor
    working_dir: "/opt/phpdoc"
